baseurl      = "https://himadrikakran.com"
title        = "My Website"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
enableEmoji  = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "Software Engineer // Foodie // Boxer"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  customCSS = ["/static/style.css"]

  # Metadata mostly used in document's head
  description = "My new homepage"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "light"

  # [params.portrait]
  #  path = "/static/portrait.jpg"
  #  alt = "Portrait"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/HimadriKakran"

  [[params.social]]
    name = "email"
    url  = "mailto:himadrik05@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/hkakran"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/himadrik"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Himadri Kakran"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd /home/himadri"
      logoHomeLink = "/"

  # And you can even create generic menu
  # [[menu.main]]
  #  identifier = "blog"
  #  name       = "Blog"
  #  url        = "/posts"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"